- .github/workflows/lint.yml
- .github/workflows/release.yml
Pin github and third party actions to known sha(s). 
Related to #3
> Pin github and third-party actions to known sha(s)

- .github/workflows/release.sh
- .github/workflows/release.yml
Generates a sha256 file for the tarball in a release.
Closes #2
> Generate and attach a sha256 txt file for releases

- .github/workflows/release.sh
sha256sum is not installed on GH runners, this commit adjusts the script to use the default shasum utility on mac os. 
Relates to #2
> Use shasum vs sha256sum

- .github/workflows/lint.yml
- .github/workflows/release.yml
Even if the tags move, the commits won't, but in that case we'll have a notion of what changed and what to look for, too.
> Add version-related comments to ease the way we relate to .yml GHA files

- .git-blame-ignore-revs
- .github/workflows/release.sh
The main important difference in this one is:
```diff
-    shasum -a 256  "$file" > "${macos_vsn}-OTP-${OTP_VSN}-sha256.txt"
+    shasum -a 256  "$file" > "${macos_vsn}-OTP-${OTP_VSN}.sha256.txt"
```
Lemme know, however, where the issue is: do you prefer `.sha256` or `-sha256`?
> Fix release flow

- .github/workflows/release.sh
- README.md
Started by adding a note on `.sha256.txt` to the `README`, then in the same context decided to fix some spelling, tweak white space, and fix the tag reference, as well as improving the description on the format of `_RELEASES` and adding a note on our future security-related aims (partly already mentioned in this repo's Issues).
> Add a note on checksums and _RELEASES

- .github/workflows/release.yml
If the branch is not `main` we don't do the release.
Of course, this is not perfect because the release step is the one that might fail, but since it's the last one it should be easier to reason on, given the reduced scope (in `main`).
Closes #11.
> Implement "dry run" on non-main branches

- .github/workflows/release.sh
Since we force our pull requests to be updated as per `main`, as well as forcing a pull request to exist before we merge to that branch, this seems like an Ok compromise, for the time being. All of this might just be wishful thinking, but I want:
1. an updated `_RELEASES` to use outside of this repo.
2. a tag in `main` that contains that update and allows to create the releases
> Create a pull request per version build (and auto-approve it)

- .github/workflows/release.sh
- .github/workflows/release.yml
We were doing `git show-ref` in the context of `kerl`'s checkout, so it'd always fail 😄 
Also, we now use GHA to create and approve the `_RELEASES` updates' pull requests:
1. creates release branch
2. updates `_RELEASES`
3. pushes `_RELEASES`
4. creates PR
5. merges PR
> Fix checkout and verify tag

- .github/workflows/release.sh
- .github/workflows/release.yml
- README.md
We were looking for the tag, inside the `_RELEASES` file, when we should be looking for the filename (no ext.).
Perhaps they were the same at a point in time and this bug just slipped through the cracks.
> Fix verification for existing version

- .github/workflows/release.sh
- .github/workflows/release.yml
We are able to avoid a shellcheck disable.
Good thing we're using bash, since now `local` is available.
Returning from a function still feels like a hack, though.
We use `local` whenever a variable is supposed to be function-local alone, and we name the other ones as `global_...` for readability/maintenance.
We get rid of global functions that shouldn't be.
Notable exceptions are variables we export, like `MAKEFLAGS`, or `KERL_BUILD_DOCS`
We make exit values explicit.
We go back to using `$1` with a comment instead of local variables, where this would just bloat the script.
Also, on attempting release, don't fail if we don't generate files (assume everything went Ok before).
This may happen if we actually determine there's nothing to generate (search for `exit 0` in `release.sh`)
> "Fix" as per `kerl` POSIX-sh lessons learned

- .github/workflows/release.sh
- .github/workflows/release.yml
We were off-by-one because of not pulling `main` after `pr merge`.
Also, with the fix to the script, the `yml` bit is not required anymore.
> Fix release and tag commit ref.(off-by-one)

- .github/workflows/release.sh
Small fix, that would only be relevant (atm) when OTP 27 -rc came out (and a previous 24, 25, or 26 was updated, tagged and released), but we might as well fix it now.
> Avoid release candidates when searching for latest OTP version

- .github/workflows/nightly.yml
- .github/workflows/release.sh
- .github/workflows/release.yml
- README.md
- SECURITY.md
Closes #4.
ℹ️ I wouldn't mind downloading and compiling OpenSSL, but wouldn't that mean we'd have to have a matrix for "OpenSSL vsn to darwin vsn"? Or should we just go with 1.1 for now and care about that later?
⚠️ I'm gonna go over https://github.com/erlang/otp/issues/4389 with open 👀 and (potentially) update our code as per [Sverker's suggestion](https://github.com/erlang/otp/issues/4389#issuecomment-776587286). @starbelly, do you know if `--disable-dynamic-ssl-lib` is honoured these days, though, and configuration doesn't fall back to dynamic linking if static fails?
- 24.0 added /usr/local/opt/openssl to the openssl configure search path
- this helps us some
- 24.0 has configure scripts in crypto and erts ... fail if a requested feature cannot be enabled... It is now better at …
> Use static OpenSSL linking

- .github/workflows/release.sh
I'm creating this as a draft for testing purposes, but it's possible it becomes required to merge. My thinking is that if build fails it should not be possible to check the output log, because the action would exit with `1`, but it seems it doesn't, so I might be missing a detail.
Closes #&lt;issue&gt;.
> Output build log

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- README.md
I'm acting on GitHub Actions' output:
```
You are using macOS 12.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```
> Remove macOS 12 from build pipelines

- .github/actions/build-and-release/action.yml
- .github/actions/get-branch/action.yml
- .github/workflows/nightly.yml
- .github/workflows/release.sh
- .github/workflows/release.yml
As per the title.
⚠️ this also fixes the "comparison to 25.1 as oldest supported" which I found out while testing in GitHub. Once merged this'll start creating `-rc` versions also 😄 and hopefully by tomorrow it'll have reached 27.0.1
Closes #360.
> Use composite actions to simplify maintenance

- .github/workflows/release.sh
> Exit with error when static linking fails

- .DONT_BUILD
- .github/workflows/release.sh
Title is self-explanatory.
**Edit**: actually, I think both `-rc3`'s and `-rc2`'s issues are coming from `ex_doc`'s download, so I'll try to fix that first.
In any case, I intend on leaving the `.DONT_BUILD` mechanism in place as it might be useful:
1. in the future
2. to debug stuff
> Bypass (same as before but) for a different version 27.0-rc3 on macOS 13

- .github/workflows/nightly.yml
- .github/workflows/release.sh
- .github/workflows/release.yml
- README.md
... nightly, the same as with `master` and `maint`.
Closes #461.
> Also build for `maint-25`, `maint-26`, and `maint-27` (per our current support range)

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- README.md
From [Actions: macOS 15 is now available for GitHub-hosted runners (GA)](https://github.com/github/roadmap/issues/986).
> Support macOS 15
